---

- name: deploying files to managed hosts
  hosts: all
  vars:
    - user: matt
  tasks:
  
  - name: Touch a file and set permissions
    file:
      path: /path/to/file
      owner: user1
      group: group1
      mode: 0640
      state: touch

  - name: Copy a file to managed hosts
    copy:
      src: file
      dest: /path/to/file
  
  - name: Retrieve SSH key from reference host
    fetch:
      src: "/home/{{ user }}/.ssh/id_rsa.pub"
      dest: "files/keys/{{ user }}.pub"

  - name: Add a line of text to a file
    lineinfile:
      path: /etc/httpd/conf/httpd.conf 
      regexp: '^ServerAdmin'
      line: ServerAdmin somebodyd@somewhere.net
  
  - name: Add additional lines to a file
    blockinfile:
      path: /path/to/file
      block: |
       First line in the additional block of text
       Second line in the additional block of text 
      state: present
  
  - name: Make sure a file does not exist on managed hosts or removing file from managed hosts
    file:
      dest: /path/to/file
      state: absent
  
  - name: synchronize local file to remote files
    synchronize:
      src: file
      dest: /path/to/file

#below is guided exercise

- name: Use the fetch module to retrieve secure log files
  hosts: all
  remote_user: root
  tasks:
  - name: Fetch the /var/log/secure log file from managed hosts
    fetch:
      src: /var/log/secure
      dest: secure-backups
      flat: no  
      #Use the flat: no parameter to
      #ensure the default behavior of appending the host name, path, and file name to the destination: